# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
encoding: UTF-8
lang: ja # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/
theme: jekyll-theme-simple-texture

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

title: まひるのゆめ
email: yasuko@say.topaz.ne.jp
description: >- # this means to ignore newlines until "baseurl:"
  作成中
baseurl: "/mahirunoyume" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yas_saw
github_username:  yasuko-sawayama
author:
  name:
  job_title:
  location:
  email: yasuko@say.topaz.ne.jp
  social_links:
    - name: github
      url: https://github.com/yasuko-sawayama
    - name: twitter
      url: https://twitter.com/yas_saw

home:
  section1: <h1>まひるのゆめ</h1>
  section2: <p>二次創作小説サイトです。</p><p>各作品はファンフィクションです。原著作者との関係はありません。</p>
  section3: 
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License. 
  footer_content: 二次創作小説サイトです。各作品はファンフィクションです。原著作者との関係はありません。

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/

# Build settings
markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
