# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
encoding: UTF-8
lang: ja # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/
theme: jekyll-theme-simple-texture
remote_theme: yizeng/jekyll-theme-simple-texture
google_analytics: UA-120641112-1
whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3
  hard_wrap: true

sass:
  style: compressed

# Exclude from processing.
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]

# Site Settings

title: まひるのゆめ
email: yasuko@say.topaz.ne.jp
description: >- # this means to ignore newlines until "baseurl:"
  自作の二次小説置き場にしたいです。作成中。今のところFGOの予定
baseurl: "/mahirunoyume" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yas_saw
github_username:  yasuko-sawayama
author:
  name: やすこ
  job_title:
  location:
  email: yasuko@say.topaz.ne.jp
  social_links:
    - name: github
      url: https://github.com/yasuko-sawayama
    - name: twitter
      url: https://twitter.com/yas_saw

home:
  section1: <h1>まひるのゆめ</h1>
  section2: <p>二次創作小説サイトです。</p><p>各作品はファンフィクションです。原著作者との関係はありません。</p>
  section3: 
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License. 
  footer_content: 二次創作小説サイトです。各作品はファンフィクションです。原著作者との関係はありません。

paths:
  home: /
  blog: /blog/
  novels: /novels/
  categories: /blog/categories/
  tags: /blog/tags/
# End

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: "/assets/images/theme/flower.png"

# Collections settings
collections:
  # 3.7.5~に上げたら使う
  # collections_dir: novels
  un_bel_di_vedremo:
    title: ある晴れた日に
    sequence: 1
    leyout: article
    output: true
# End
